const data = {
  "IN-AP": {
    name: 'Andhra Pradesh',
    capital: 'Amaravati',
    videoUrl: 'Andhra.mp4',
    stateTourismWebsite: 'https://tourism.ap.gov.in/',
    slogan: 'The Essence of Incredible India',
    description: 'Andhra Pradesh presents a glorious synthesis of culture against a colourful natural backdrop. &amp;nbsp;Varied wildlife, rich history, vivid culture, majestic architecture make Andhra Pradesh a destination of endless surprises. Welcoming visitors with innumerable charming facets Andhra Pradesh captivates the eager traveller, looking for a wonderful holiday experience.Andhra Pradesh Tourism has always been the frontrunner in attracting greatest number of tourists, inland and foreign, as it boasts of a naturally, ecologically, culturally and religiously rich and diverse variety of tourist destinations that are treasures of visual treat where one can continuously explore new experiences of visitor gratification and delight. Bounding in natural resources, the state of Andhra Pradesh having the longest eastern coastline and with a trail of Buddha Period glory, houses and holds many heritage sites adorned with pristine splendour, the forts, citadels and architectural masterpieces built by the past Royal hegemony and its noble Emperors. The magnificent palaces and places, monuments, memorials, tombs and stately structures built by them reflect the art and craftsmanship, architecture and culture that originated on this land.There are beautiful dams, valleys, hills and ridges with the scenic dale, tranquil lake waters, swirling beach waves, meadows, resorts, hill stations, caves, virgin forests, sanctuaries and national parks which a visitor can enjoy to his heart&amp;#039;s content.Temples and shrines of pilgrimage are the important destinations of tourist traffic and are a big source of revenue flow. Museums and archaeological treasure houses with different galleries showcase historic and amazing collections of antiques, artefacts, weaponry and a wide range of objects that symbolize the history and culture and marvels of the territory. Festivals are year around and celebrations abound. So far an experience that never fails to excite and enchant. Welcome to Andhra Pradesh.',

  },
  "IN-AR": {
    name: 'Arunachal Pradesh',
    capital: 'Itanagar',
    videoUrl: 'ArunachalPradesh.mp4',
    stateTourismWebsite: '',
    slogan: 'The Land of Dawnlit Mountains',
    description: '“The last of the great Shangri-La.."Shangri-La is a mystical, harmonious valley" or so goes the description in James Hilton’s 1993 novel, Lost Horizon. Hilton went on to describe a Garden of Eden on Earth: a land of milk and honey in a hidden Himalayan valley, where nobody grew old or ugly. Over the years, there’s been no shortage of contenders for the title of ‘Lost Shangri-La’ but now there’s a new kid on the block: Arunachal Pradesh”. The thunderous Himalayan peaks so little known that few have been named, let alone climbed, plus jungles teeming with life forms that scientists are yet to catalogue, delicately tattooed and pierced tribal peoples living in long houses in the forest, magnificent Buddhist Temples and a severe dose of near limitless adventure. Lonely planet’s top 4 regions in the world.<br />Arunachal Pradesh, a veritable treasure house of nature, tucked away in the north eastern tip of India, invites you to relax in its picturesque hills and vales encircled on three sides by Bhutan, China and Myanmar. Come to Arunachal Pradesh to relive in nature in its full splendour. Enjoy the salubrious climate and meet its simple and hospitable people. Snowy misty, famous monasteries, unexplored passes and tranquil lakes come together to form some of the prettiest mountain spots in Arunachal Pradesh. For a tourist the options are varied, each more tempting than the other.',

  },
  "IN-AS": {
    name: 'Assam',
    capital: 'Dispur',
    videoUrl: 'Assam.mp4',
    stateTourismWebsite: 'https://tourism.assam.gov.in/',
    slogan: 'The Awesome Assam',
    description: 'Termed as the land of “Blue Hills and Red River” Assam is the gateway to the north eastern states and has been aptly described as the sentinel of Northeast India. Seven Indian States and two countries Bhutan and Bangladesh, surround Assam which is also close to India’s international borders with China and Myanmar.<br />Assam is surrounded by hills, major rivers such as Brahmaputra & Barak and its tributaries, thick forest, tea gardens which enhances the scenic beauty of Assam. Infact the mighty Brahmaputra river of Assam is the only male river in the country.<br />The state is dotted with monuments of 600 years old Ahom dynasty; the longest ruling single dynasty in Indian history. It was one among the very few dynasties that could not be conquered by the Mughals. Assam is the home to various ethnic tribes and groups, each having its own cultural heritage and unique features in its socio-cultural life including customs, religious belief, language, culture, way-of-life, food, songs, festivals including Bihu, Baishagu, Rongker & Chomangkan Festival, Bishu, Baikho, Ali-Aye-Ligang, Me-Dum-Me-Phi, Ambubachi Mela and many more.<br />Assam is a home to Five National Parks and 18 Wildlife sanctuaries, the highest concentration in India, are host to 25 percent of India’s floristic wealth and enormous faunal diversity. The famous Kaziranga National Park is located in the Golaghat district of Assam is home to largest population of world’s one horned rhino species, Wild Asiatic Water Buffalo and Eastern Swamp Deer, wild elephants as well as Migratory birds. This National Park has also the highest density of tigers. Manas National Park, also a world heritage site, is a constituent unit of the Eastern Himalayan Bio-Diversity Region; one of the two biodiversity “Hot Spot” in the country. The mystery of the birds’ suicide at Jatinga Dima Hasao District, is a subject of interest of all nature lovers and researchers.<br />The state is endowed with more than 600 tea gardens which gives soothing view to the eyes as one travels down to upper Assam. Around 20 tea gardens in Assam have developed and maintained golf courses within the garden area and a few have polo fields. The Jorhat Gymkhana Club is the oldest golf course in Asia and the third oldest in the World\<br />Located in the Nilachal hills in the western part of Guwahati, Kamakhya Temple is the oldest temple is dedicated to goddess Kamakhya. The temple is popular among pilgrims of Tantric worship, more so during the annual Ambubachi Mela Festival. Hajo is another spiritual centre where people from three religions, Buddhist, Hindus and Muslims congregate for pilgrimage.<br />The mighty river Brahmaputra decors the geography of the state and one can take a Cruise along this river with first class facilities experiencing wildlife, tradition, adventure tourism on its way. “MV Mahabaahu” a Cruise amongst the Top Ten River Cruise of the World, is of great pride for Assam. Assam is blessed with the world’s largest inhabited river island Majuli, which  has several satras vaishnavite monasteries, some dating back to the 16th centuries; as well as the world’s smallest riverine island in the world namely Umananda Temple which was built in the 17th Century dedicated to Lord Shiva.',

  },
  "IN-BR": {
    name: 'Bihar',
    capital: 'Patna',
    videoUrl: 'Bihar.mp4',
    stateTourismWebsite: 'http://www.bihartourism.gov.in/',
    slogan: 'Blissful Bihar',
    description: 'Bihar\'s antiquity is evident from its name, which is derived from the ancient word "VIHARA" (monastery). It is indeed a land of monasteries. Hindu, Buddhist, Jain, Muslim and Sikh shrines abound in this ancient land where India\'s first major empires rose and fell. Where the ruins of the worlds\' earliest university slumbers in the void of time. The passage of Ganga, flowing wide and deep enrich the plains of Bihar before distributing in Bengal\'s deltoid zone.<br />Among all Indian states, Bihar is the one most intimately linked to the Buddha’s life, resulting in a trail of pilgrimages which have come to be known as the Buddhist circuit. The Buddhist trail begins at the capital city, Patna, where a noteworthy museum contains a collection of Hindu and Buddhist sculptures as well as a terracotta urn said to contain the ashes of Lord Buddha.<br />The Buddha spent five years at Rajgir after having attained enlightenment, and many of the remains at Rajgir commemorate various incidents related to life of Buddha, the hill of Gridhrakuta being perhaps the most important, as this is where the Buddha delivered most of his sermons. Bodhgaya is the spot where Lord Buddha attained enlightenment, with the Mahabodhi Temple marking the precise location.<br />A monastic university flourished in Bihar (Nalanda) from the 5th to the 11th century. It is said to have contained nine million books, with 2,000 teachers to impart knowledge to 10,000 students who came from all over the Buddhist world. Lord Buddha himself taught here and Hieun Tsang, the 7th century Chinese traveler, was a student. Ongoing excavations have uncovered temples, monasteries and lecture halls. Rajgir, ‘the royal palace’, 12 km south, was the venue for the first Buddhist Council.<br />This landlocked state of Bihar is surrounded by Nepal, Bengal, Orissa, Madhya Pradesh, Uttar Pradesh and comprises four cultural regions-Bhojpur, Mithila and Magadha and Chotanagpur. Rivers Kosi and Gandak from the north and Sone from the south join the Ganga. In the fertile plains, rice, sugarcane, oilseeds, gram, maize, jute, barley and wheat are cultivated.  ',

  },
  "IN-CH": {
    name: '',
    capital: '',
    videoUrl: '',
    stateTourismWebsite: '',
    slogan: '',
    description: '',

  },
  "IN-CT": {
    name: 'Chhattisgarh',
    capital: 'Raipur',
    videoUrl: 'Chhatisgarh.mp4',
    stateTourismWebsite: '',
    slogan: 'Full of surprises',
    description: 'Chhattisgarh , India\'s 10th largest state is endowed with a rich culture, heritage and attractive natural diversity. Situated in the heart of India with a ten thousand years old civilisation it is a land \'Full of Surprises\' that attracts tourists who look forward to experience the pristine. Chhattisgarh is an uniquely Indian experience. Home to the country\'s widest waterfalls, caves, lush green forests, ancient monuments, rare wild life, exquisitely curved temples, Buddhist sites and hill plateaus. Chhattisgarh boasts of more than 80% of bio diversity that is not found anywhere across the country. The state has 44% of forest cover with 32% of tribal population. Chhattisgarh has become a magnet of nature enthusiasts who wish to explore unique tribal arts, crafts and traditions. For centuries its tribal communities have played a pivotal role in nurturing and protecting the natural habitat through the eco-friendly practices.Chhattisgarh offers everything to a traveller - art and architecture, heritage, handicrafts, cuisine, fairs and festivals. Chhattisgarh figures in numerous tales that form part of the two great Indian epics, the Ramayana and the Mahabharata. The state boasts of the widest waterfall in India, Chitrakote.  In monsoon when the Indravati River is in full flow, this waterfall in Bastar District becomes almost 980 ft wide!!!  Chhattisgarh has a legacy of gods and goddesses and numerous temples, both ancient and modern which attracts devotees, pilgrims and travellers throughout the year. The annual mega event \'Sirpur International Dance and Music Festival\' which is held every year at the Buddhist site of Sirpur is particularly note worthy. This state presents a curious mixture of modern and traditional way of life.',

  },
  "IN-DD": {
    name: 'Daman and Diu',
    capital: 'Daman',
    videoUrl: 'DamanDiu.mp4',
    stateTourismWebsite: 'https://www.daman.nic.in/',
    slogan: '',
    description: 'Union Territory of Daman and Diu comprises of two districts namely Daman and Diu. Both Districts are situated on western coast of India at a distance of about 700 kms. Daman is the Head Quarter of this Union Territory. Daman is on the main land, while Diu is an island!!  Both the Districts of Daman and Diu are near Gujarat State and are separated by about 700 kms from one another.',

  },
  "IN-DL": {
    name: '',
    capital: '',
    videoUrl: '',
    stateTourismWebsite: '',
    slogan: '',
    description: '',

  },
  "IN-DN": {
    name: 'Dadra and Nagar Haveli',
    capital: 'Silvassa',
    videoUrl: 'DadraNagarHaveli.mp4',
    stateTourismWebsite: 'http://www.tourismdddnh.in/',
    slogan: '',
    description: 'The Union Territory of Dadra and Nagar Haveli lies near the western coast of India and consists of two separate parts. Of these, Dadra is surrounded by the state of Gujarat, and Nagar Haveli lies on the border of Maharashtra and Gujarat. The territory has hilly terrain especially towards the north-east and east where it is surrounded by ranges of Sahyadri Mountains (Western Hills). River Daman Ganga and its three tributaries cut across this territory. The most prominent tribes are Dhodia, Kokna and Varli, with small groups of Koli, Kathodi, Naika and Dubla scattered across the territory.On 11 August 1961, it became a part of the India and was announced to be a Union Territory.As it shares borders with both Gujarat and Maharashtra, the languages spoken here are Gujarati, Hindi, Marathi, Konkani, Bhilodi and Bhili',
  },
  "IN-GA": {
    name: 'Goa',
    capital: 'Panaji',
    videoUrl: 'Goa.mp4',
    stateTourismWebsite: 'https://goa-tourism.com/',
    slogan: 'A Perfect holiday destination',
    description: 'The pocket-sized paradise of Goa is a traveller\'s dream. Sun, sea, sand, spices, spirituality and seafood, along with a balmy weather, call to the soul of trekkers, backpackers, nature lovers and those who simply want to languish in its slow-paced and relaxed vibes. Located by the glistening waters of the Arabian Sea on India’s western coast, the state of Goa is renowned for its breathtaking beaches, rich culture and pristine natural beauty. Formerly a Portuguese colony, Goa offers travellers a chance to experience a unique blend of sandy shores, forests, monuments and delectable cuisine, attracting tourists across age groups.',

  },
  "IN-GJ": {
    name: 'Gujarat',
    capital: 'Gandhinagar',
    videoUrl: 'Gujarat.mp4',
    stateTourismWebsite: 'https://www.gujarattourism.com/',
    slogan: 'Vibrant Gujarat',
    description: 'The varied landscape of Gujarat is a complete package in itself. Here, the White Desert of Kutch coexists with a long and beautiful coastline. The archaeological monuments from different eras go as far back as Harappan time in Dhola Veera and Lothal.  Gujarat has ancient caves, stupas, monasteries, temples and monuments that exhibit the Indo-Sarcenic architectural style which blends elements of Islamic and Hindu architecture. The capital of Gujarat, Gandhinagar is India’s first UNESCO accredited World Heritage City. Gujarat is also a delightful destination for the eco traveller. It is the abode of endangered wild life like the Asiatic Lion and Indian Wild Ass, not seen anywhere else in India.',
  },
  "IN-HP": {
    name: 'Himachal Pradesh',
    capital: 'Simla',
    videoUrl: 'HimachalPradesh.mp4',
    stateTourismWebsite: '',
    slogan: 'Unforgettable Himachal',
    description: 'Himachal situated in the heart of the western Himalaya, identified as "Dev Bhumi" and is believed to be the abode of Gods and Goddesses. The entire State is punctuated with stone as well as wood temples. The shadowy valleys, rugged crags, glaciers and gigantic pines and roaring rivers and exquisite flora and fauna compose the symphony that is for ever Himachal. The State has a rich treasure of places of pilgrimage and of anthropological value. The State has also the pride of being the home to rishis like Vyas, Parashar,Vashist, Markandey and Lamas, etc.',

  },
  "IN-HR": {
    name: 'Haryana',
    capital: 'Chandigarh',
    videoUrl: 'Haryana.mp4',
    stateTourismWebsite: 'http://haryanatourism.gov.in/',
    slogan: 'A pioneer in Highway Tourism',
    description: 'The name Haryana means the abode of God. It is a blend of two Sanskrit words ‘Hari’ which means God and ‘ayana’ meaning home. It is a land where guests are treated equal to god.Haryana represents the face of modern India. The one which is heralding the future yet prides itself of being rooted in its magnificent culture. Today Haryana is positioned among one of the wealthiest and most economically developed regions in South Asia.',
  },
  "IN-JH": {
    name: 'Jharkhand',
    capital: 'Ranchi',
    videoUrl: 'Jharkhand.mp4',
    stateTourismWebsite: 'http://jharkhandtourism.gov.in/',
    slogan: 'A New Experience',
    description: 'Jharkhand is endowed with rich cultural heritage and bestowed liberally with bounties of nature. The State is kaleidoscope of past splendours and present glory. A fascinating State with luxuriant forest, captivating wild life, enthralling water falls, exquisite handicrafts, adventure tourism, sprawling water bodies, enchanting classical and folk dances and music and above all hospitable and peace loving people. The State of Jharkhand is blessed with immense bio-diversity, moderate climate, rich cultural and historical heritage, religious places of worship and ethnic aspects to make the State the ultimate destination for tourists. The lush green forests, rivers and waterfalls of this primeval land are home to many kinds of spectacular flora and fauna. Age-old tribes are the main inhabit of this wonderful land, the state is also a hubs of industry, commerce and education.',
  },
  "IN-JK": {
    name: 'Jammu and Kashmir',
    capital: 'Srinagar',
    videoUrl: 'Kashmir.mp4',
    stateTourismWebsite: 'http://www.jktourism.org/',
    slogan: 'Chalo Kashmir',
    description: 'The Union Territory of Jammu and Kashmir is a great tourist destination. Picturesque and enchanting, Kashmir is cradled high in the lofty green Himalayas and hailed all over the world for its incredible natural beauty. Surrounded by mountain peaks, lush green valleys, glistening lakes, temples and spectacular Mughal-era gardens, it has inspired poets through centuries. Kashmir is crisscrossed by chinar tree-lined roads and quaint wooden bridges; and is home to bustling bazaars, sufi shrines and forts. Add to this, the charms of flavourful Kashmiri cuisine and apples and walnuts from the lush orchards surrounding it.',
  },
  "IN-KA": {
    name: 'Karnataka',
    capital: 'Bengaluru',
    videoUrl: 'Karnataka.mp4',
    stateTourismWebsite: 'http://www.karnatakatourism.org/',
    slogan: 'One State Many Worlds',
    description: 'A land known for its silks, spices and sandalwood, Karnataka adds up as an experience to remember for a lifetime. Tourism in Karnataka stands out with its diverse offerings that include wildlife & national parks, monuments & heritage sites, beaches and pilgrimage sites. Yet another notable point is that tourist attractions in Karnataka are located at geographically extreme ends which interestingly make the capital Bengaluru (Silicon Valley of India), the focal point of tour itineraries.',
  },
  "IN-KL": {
    name: 'Kerala',
    capital: 'Thiruvananthapuram',
    videoUrl: 'Kerala.mp4',
    stateTourismWebsite: 'https://www.keralatourism.org/',
    slogan: 'God\'s own country',
    description: 'Kerala is blessed with a unique set of geographical features that have made it one of the most sought after tourist destinations in Asia. A long shoreline with serene beaches, tranquil stretches of emerald backwaters, lush hill stations and exotic wildlife, are just a few of the wonders. Most of the state is engulfed in rich greenery which ensures a very calming experience at all times. Bestowed with a pleasant and equable climate throughout the year, Kerala is a tropical land where one can relax and be at ease',
  },
  "IN-LD": {
    name: 'Lakshadweep',
    capital: 'Kavaratti',
    videoUrl: 'Lakshadweep.mp4',
    stateTourismWebsite: 'http://www.lakshadweep.nic.in/',
    slogan: 'An alluring archipelago',
    description: 'Lakshadweep is one of the worlds most spectacular tropical island systems. Thirty- two sq. km of land spread over 36 islands surrounded by 4200 sq. km of lagoon rich in marine wealth. The precious heritage of ecology and culture is supported by an extremely fragile ecosystem. Committed to the cause of Eco tourism Union Territory of Lakshadweep has consciously followed a middle path between tourism promotion and environmental conservation. The Administration is carefully monitoring the environmental impact of coastal tourism and has taken steps to promote tourism in a way that is consistent with ecological concerns. As an effective strategy to avoid pressure on ecological environment, the efforts to promote tourism have been synchronized with the carrying capacity of the islands.',
  },
  "IN-MH": {
    name: 'Maharashtra',
    capital: 'Mumbai',
    videoUrl: 'Maharashtra.mp4',
    stateTourismWebsite: 'https://www.maharashtratourism.gov.in/',
    slogan: 'Unlimited',
    description: 'The spirit of Maharashtra is cosmopolitan, forward-thinking, tolerant and vibrant. There is enough to keep connoisseurs of temples, forts, old monuments and art---gainfully preoccupied here. Forts have played a vital role in the history of the state, given the rocky terrain of the Sahyadris.  Each fort marks a military triumph, and each tells a story of strategy, warfare, intrigue and planning. All of them reconstruct the tale of an enterprising leader , Chhatrapati Shivaji- in the Deccan arena, who with fortitude went onto become one of the tallest kings of Indian history. Bombay or Mumbai—the capital of Maharashtra is not only seen as the financial capital of India, but is literally the Gateway of India which is secular, progressive yet rooted. It is also home to the largest film industry in the world, an industry whose turnover is more than that of the GDP of several small nations.',
  },
  "IN-ML": {
    name: 'Meghalaya',
    capital: 'Shillong',
    videoUrl: 'Meghalaya.mp4',
    stateTourismWebsite: 'http://megtourism.gov.in/',
    slogan: 'Half way to Heaven',
    description: 'Meghalaya is richly endowed with natural beauty. Everywhere you go, you will never cease to be mystified by the spectacular charm the state offers; from cascading waterfalls, lush green forests, deep caves, amazing and mesmerising culture and tradition to hospitable and friendly people. Visit us and be charmed and captivated for life.',
  },
  "IN-MN": {
    name: 'Manipur',
    capital: 'Imphal',
    videoUrl: 'Manipur.mp4',
    stateTourismWebsite: 'http://www.manipurtourism.gov.in/',
    slogan: 'Jewel of Incredible India',
    description: 'Manipur is strategically located in the North-eastern corner of India bordering Myanmar. The state serves as a corridor for India to the South East Asian countries and offers immense possibilities for growth of tourism and regional business. Adorned with a variety of breath-taking locations, the state is indeed a paradise on Earth where Mother Nature has been extra generous in her bounty. Least touched and least discovered, Manipur is a promising tourist destination for adventure and nature lovers alike.',
  },
  "IN-MP": {
    name: 'Madhya Pradesh',
    capital: 'Bhopal',
    videoUrl: 'MadhyaPradesh.mp4',
    stateTourismWebsite: 'http://www.mptourism.com/',
    slogan: 'The heart of Incredible India',
    description: 'Madhya Pradesh can be described as the best state of the nation when it comes to the diversity of its tourism destinations.Madhya Pradesh is known as the “Heart of India” because of a lot many things that it has to offer. It has been home to cultural and spiritual heritage of almost all the religions. Innumerable monuments, intricately carved temples, stupas, forts and palaces are dotted all over the State. The natural beauty of the state is equally varied. Consisting largely of a plateau, the State has everything, from mighty mountain ranges to meandering rivers to miles of verdant forests. In fact a large part of Madhya Pradesh is under the forest cover, offering a unique and exciting panorama of wildlife. In the National Parks of Kanha, Bandhavgarh and Pench you can spot the tiger, bison and a wide variety of deer and antelope. Water sports, caravan journeys, river cruise, sound and light shows, tribal life, Madhya Pradesh has everything for every travel thirsty soul.',
  },
  "IN-MZ": {
    name: 'Mizoram',
    capital: 'Aizawal',
    videoUrl: 'Mizoram.mp4',
    stateTourismWebsite: 'https://tourism.mizoram.gov.in/',
    slogan: 'Peace pays',
    description: 'Mizoram, the land of the Mizos or the Highlanders who belong to the Mongoloid race, exudes an exotic charm of its own.   Mizoram is a mountainous state nestling in the southern tip of the north-east region of India. From the lush forests dominated by thick bamboo groves, numerous waterfalls that gush down the narrow gorges to confluence into large meandering streams in the deep valleys, dotted with unique landmarks of myriad folklores and picturesque villages of houses built on stilts, Mizoram is a land of dramatic seas of morning mists that enfold islands of hills and peaks.',
  },
  "IN-NL": {
    name: 'Nagaland',
    capital: 'Kohima',
    videoUrl: 'Nagaland.mp4',
    stateTourismWebsite: 'http://tourismnagaland.com/',
    slogan: 'Land of Festivals',
    description: 'Tourism in Nagaland is on growing stage with its glorious past and rich heritage and culture. For the adventurous and the intrepid, Nagaland is an ideal place for trekking, rock climbing , jungle camping and offers limitless exploration possibilities in its lush and verdant sub-tropical rain forests which are also a treasure trove of a plethora of medicinal plants. Above and beyond tourists can also experience a truly ethnic Naga Culture with the best local brews served in large bamboo mugs and exotic local cuisines which is much celebrated here.',
  },
  "IN-OR": {
    name: 'Odisha',
    capital: 'Bhubaneshwar',
    videoUrl: 'Odisha.mp4',
    stateTourismWebsite: 'http://www.odishatourism.gov.in/',
    slogan: 'The soul of Incredible India',
    description: 'The State of Odisha situated in the eastern seaboard of Indian subcontinent is endowed with amazing array of incredible tourism products. Traditionally, famous as a hub of cultural destination, but of late has emerged as one of the beautiful state in the country with rapid progress in all front including travel & tourism sector.',
  },
  "IN-PB": {
    name: 'Punjab',
    capital: 'Chandigarh',
    videoUrl: 'Punjab.mp4',
    stateTourismWebsite: 'http://punjabtourism.gov.in/',
    slogan: 'India begins here',
    description: 'Deriving its name from five full-bodied rivers–Sutlej, Beas, Ravi, Jhelum, and Chenab–which flow through its vast plains, Punjab is representative of abundant things.Punjab is a land of ethnic and religious diversity, having borne and shaped a number of religious movements that include Sikhism, Buddhism and Sufism. The Punjabi language, too, finds its origin in the Indo-European linguistic family that includes Persian and Latin. Naturally replete with fertile soils and rich water sources, it is primarily an agricultural state, and has continually and infinitely contributed towards the food security of the Indian Republic.',
  },
  "IN-PY": {
    name: '',
    capital: '',
    videoUrl: '',
    stateTourismWebsite: '',
    slogan: '',
    description: '',

  },
  "IN-RJ": {
    name: 'Rajasthan',
    capital: 'Jaipur',
    videoUrl: 'Rajasthan.mp4',
    stateTourismWebsite: 'http://www.tourism.rajasthan.gov.in/',
    slogan: 'The incredible state of India',
    description: 'Rajasthan, the Land of Kings is synonymous to heroism, royalty and honour. Historic tales of battles fought and romance of the riches adorn the walls of the state. Established in the era marked with wartime ballads yet living in the modern period, this beautiful region is a travellers\' destination. Those looking out for the remnants of the past should not pass up a trip to Rajasthan. For wanderers interested in adventures at the various landscapes should definitely get a glimpse of this venturesome state. And for the ones who plan to have a quiet sojourn gazing at the beauty of the golden sand dunes, Rajasthan tops your list. This land is a colourful melange of massive forts, stunning palaces, diverse cultures, delectable cuisines and warm people, set amidst a rugged yet inviting landscape. Come, explore the miscellany of the old and the new in Rajasthan, a glittering jewel of India.',
  },
  "IN-SK": {
    name: 'Sikkim',
    capital: 'Gangtok',
    videoUrl: 'Sikkim.mp4',
    stateTourismWebsite: 'http://www.sikkimtourism.gov.in/',
    slogan: 'Small but Beautiful',
    description: 'Sikkim situated in the Eastern Himalayan region with an area of 7,096 sq km and altitude ranging from 300m to 8,586m above sea level is a wonderland blessed with natural abundance from icy cold deserts, flowering alpine meadows, to lush green forests and emerald mountain lakes. The crowning glory of this wonderland is undoubtedly the magnificent Mt. Khangchendzonga (8,586m), the third highest mountain of the world. The mountain is not merely a physical entity but the abode of guardian deity whose benign watchfulness ensures peace and prosperity of the land.',
  },
  "IN-TG": {
    name: 'Telangana',
    capital: 'Hyderabad',
    videoUrl: 'Telangana.mp4',
    stateTourismWebsite: 'https://telanganatourism.gov.in/',
    slogan: 'It\'s all in it',
    description: 'Telangana, the 29th and youngest state of India, formally recognized on June 2, 2014 is a treasure trove of tourist destinations. Telangana is known for its hospitality and multicultural and pluralistic society. Hyderabad, the capital city of this state is the fifth largest city in India and home to some of India\'s best educational institutions, public sector and defence companies and a thriving global services sector and film industry and known for its world famous Hyderabadi Biryani.',
  },
  "IN-TN": {
    name: 'Tamil Nadu',
    capital: 'Chennai',
    videoUrl: 'TamilNadu.mp4',
    stateTourismWebsite: 'http://www.tamilnadutourism.org/',
    slogan: 'Enchanting Tamil Nadu',
    description: 'Tamil Nadu is the eleventh largest state in India by area, sixth-most populous state according to the Human Development Index in 2011 and is the second - largest state economy in India after Maharashtra.  Its official language is Tamil, which is one of the longest surviving classical language in the World.  Chennai is the capital of Tamil Nadu. Tamil Nadu has all segments of Tourist attractions which invite tourists.  It has cerulean mountains, silver waterfalls, verdant vegetation, sandy beaches, mammoth monuments, timeless temples, fabulous wildlife, scintillating sculptures and reverberating rural life.  It has picturesque spots, continuing heritage, cultural confluence and aesthetic magnificence.',

  },
  "IN-TR": {
    name: 'Tripura',
    capital: 'Agartala',
    videoUrl: 'Tripura.mp4',
    stateTourismWebsite: 'http://www.tripuratourism.gov.in/',
    slogan: 'Visit Agartala',
    description: 'Dangling between North East India and Bangladesh, the state of Tripura is tucked in mythology, and a history of over 2,500 years and 186 kings. According to the \'Rajmala\’, Tripura’s celebrated court chronicle, an ancient king named \'Tripur\' ruled over these territorial domains, which explains the current name. Tripura’s peacefully pristine co-existence down the annals of time, constitute its irresistible charm as a tourist destination. The diversity of cultural streams and faiths, ancient temples, an epic history, spellbinding archaeology, handicrafts, traditional arts and music, bountiful biodiversity, and flushing meadows are but a few of the experiences of Tripura.',
  },
  "IN-UP": {
    name: 'Uttar Pradesh',
    capital: 'Lucknow',
    videoUrl: 'UttarPradesh.mp4',
    stateTourismWebsite: 'http://www.uptourism.gov.in/',
    slogan: 'Amazing heritage, Grand Experiences',
    description: 'Uttar Pradesh is one of the states that aesthetically defines India and its rich history that’s as ancient as the time known. This is the land wherein great sages have emerged, religions evolved and two great epic of India: Ramayana and Mahabharata have been inspired from. With each progressing century, the state has vouched for the secularity of India by giving home to various religions: Hindu, Jainism, Islamic, Buddhist and more.',
  },
  "IN-UT": {
    name: 'Uttarakhand',
    capital: 'Dehradun',
    videoUrl: 'Uttarakhand.mp4',
    stateTourismWebsite: 'https://uttarakhandtourism.gov.in/',
    slogan: 'Exploring Uttarakhand',
    description: 'Uttarakhand, a state in northern India crossed by the Himalayas, is known for its Hindu pilgrimage sites. Rishikesh, a major centre for yoga study, was made famous by the Beatles’ 1968 visit. The city hosts the evening Ganga Aarti, a spiritual gathering on the sacred Ganges River. The states forested Jim Corbett National Park shelters Bengal tigers and other native wildlife.',
  },
  "IN-WB": {
    name: 'Bengal',
    capital: 'Kolkata',
    videoUrl: 'Bengal.mp4',
    stateTourismWebsite: 'https://www.wbtourismgov.in/',
    slogan: 'Beautiful Bengal',
    description: 'West Bengal has got heterogeneous geographical division with countless natural assets, stretching from Darjeeling Himalayan range of mountains in the north to the Gangetic Plain in the south, from quiet beaches across the coastal region to the world’s largest Delta which is also known for being the natural habitat of wild scarce species of Royal Bengal tigers at mangrove estuaries of Sundarbans, from green varied landscapes to vast historical events starting from ancient  & classical period, medieval & early modern period, colonial period to independence and afterwards.',
  },
}